### ISSUE TITLE
a problem when compiling vio_g2o

### ISSUE THREAD

**Issue by zhm1995** [JzHuai0108/vio_g2o#1]
I followed the steps mentioned by you and all the other files could be compiled except this one.
I download eigen3.2.10.
this only two of all error message, in fact there are plenty of it.
Would you please take a look? I will be very grateful!!

```
/usr/include/c++/4.8/complex:393:5:` note:   template argument deduction/substitution failed:
/home5/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_g2o/src/IMU_constraint.cpp:670:90: note:   ‘const Sophus::SE3Group<double>’ is not derived from ‘const std::complex<_Tp>’
                                     (params_imu.T_imu_from_cam*T_c2_from_world->estimate()).data()};
                                                                                          ^
In file included from /usr/local/include/eigen3/Eigen/Core:28:0,
                 from /usr/local/include/eigen3/Eigen/Dense:1,
                 from /home5/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_common/include/vio/IMUErrorModel.h:4,
                 from /home5/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_common/include/vio/IMUErrorModel.cpp:1,
                 from /home5/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_g2o/include/vio_g2o/IMU_constraint.h:5,
                 from /home5/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_g2o/src/IMU_constraint.cpp:2:
/usr/include/c++/4.8/complex:384:5: note: template<class _Tp> std::complex<_Tp> std::operator*(const std::complex<_Tp>&, const std::complex<_Tp>&)
     operator*(const complex<_Tp>& __x, const complex<_Tp>& __y)
     ^
```
```
/home5/Zlb/Sophus-master/sophus/se3.hpp:1026:48: warning: non-static const member ‘const Eigen::Map<const Eigen::Matrix<double, 3, 1>, 0, Eigen::Stride<0, 0> > Eigen::Map<const Sophus::SE3Group<double> >::translation_’ in class without a constructor [-Wuninitialized]
   const Map<const Matrix<Scalar,3,1>,_Options> translation_;
                                                ^

```

**Comment by JzHuai0108** [comment]
Thanks for your interest in my work. I think it is possible there are multiple copies of Eigen installed on your computer. My suggestion is to pass -DEIGEN_INCLUDE_DIR="/your/path/to/include/eigen3 as argument to the cmake command in building vio_g2o. Meanwhile, I have updated readme.md and build.sh for ORBSLAM_DWO (https://github.com/JzHuai0108/ORB_SLAM) to prevent issues caused by multiple copies of Eigen or OpenCV installed on the computer.

**Comment by zhm1995** [comment]
There is still this problem..
It seems like a problem with sophus, but sophus builds well..
 
Here is the error message.. Would please take a look again.. I am so sorry to bother you

```
[ 33%] Building CXX object CMakeFiles/vio_g2o.dir/src/IMU_constraint.cpp.o
In file included from /home5/skk/Zlb/Sophus-master/sophus/se3.hpp:27:0,
                 from /home5/skk/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_g2o/include/vio_g2o/anchored_points.h:7,
                 from /home5/skk/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_g2o/include/vio_g2o/IMU_constraint.h:6,
                 from /home5/skk/Zlb/catkin_ws/src/orbslam_dwo/Thirdparty/vio_g2o/src/IMU_constraint.cpp:2:
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:127:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:136:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:154:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:164:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:177:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:190:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:205:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
/home5/skk/Zlb/Sophus-master/sophus/so3.hpp:219:3: error: ‘EIGEN_DEVICE_FUNC’ does not name a type
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
   ^
```

**Comment by JzHuai0108** [comment]
You probably need to pull a specific commit of sophus by

        git clone https://github.com/stevenlovegrove/Sophus.git
	cd Sophus
	git checkout b474f0

**Comment by zhm1995** [comment]
Thank you so much.. I'll try it later..
//May I ask you another question?
//Do you use the imu information only in trackmotionmodel ? In code, the optimization part only concerns images .. 
(sorry, I found it in LocalOptimize...)

By the way, the typesetting in readme has some problems in github.

**Comment by zhm1995** [comment]
I have successfully compiled them all.

And there are these problems maybe you could add into readme..
1. In vio_g2o/CMakeLists, add Thirdparty/g2o & Thirdparty/g2o/build  to  include_dir 
add Thirdparty/g2o/lib to lib_directories
2. In orbslam_dwo/CMakeLists , do the first step..

These are my own debugging.. thank you very much

**Comment by JzHuai0108** [comment]
Good comment. Currently, to compile vio_g2o, the G2O_INSTALL_PREFIX needs to be passed to the cmake command, i.e., -DG2O_INSTALL_PREFIX=/path/to/g2o/local_install. Doing so, you don't need to change vio_g2o/cmakelists.txt or orbslam_dwo/cmakelists.txt.

**Comment by zhm1995** [comment]
Dear JzHuai
 Would you please leave an email for me?
 I still have some problems about your code..
